version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  
    container_name: frontend-app
    environment:
      - NODE_ENV=development
      - HOSTNAME=0.0.0.0  
    ports:
      - "3000:3000"  
    volumes:
      - .:/app  
      - /app/node_modules 
    command: ["npx", "nodemon", "--legacy-watch", "--ext", "js,jsx,ts,tsx", "--exec", "npm", "run", "dev"]
    restart: always
